steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
# Deploy
- name: 'gcr.io/cloud-builders/gcloud'
  args: ["app", "deploy", "prod.app.yaml", "--no-promote", "--verbosity=debug"]
  timeout: 600s