import Vue from "vue";

import { library, dom } from "@fortawesome/fontawesome-svg-core";
import {
  faAddressCard,
  faArrowLeft,
  faAssistiveListeningSystems,
  faBell,
  faBars,
  faCamera,
  faCaretDown,
  faChartBar,
  faChartLine,
  faChartPie,
  faChevronDown,
  faChevronRight,
  faCircle,
  faCog,
  faCommentAlt,
  faCommentDots,
  faDownload,
  faEdit,
  faEnvelope,
  faEraser,
  faExclamationCircle,
  faFileCode,
  faFileCsv,
  faFileExcel,
  faFilter,
  faKey,
  faLaptop,
  faLevelUpAlt,
  faListOl,
  faLock,
  faMinus,
  faPhone,
  faPlay,
  faPlus,
  faQuestion,
  faReceipt,
  faRedo,
  faSearch,
  faShoppingCart,
  faSignOutAlt,
  faSpinner,
  faSquare,
  faStop,
  faTable,
  faTimes,
  faTrash,
  faUndo,
  faUnlock,
  faUser,
  faUserCheck,
  faUserCog,
  faUsers
} from "@fortawesome/free-solid-svg-icons";
import {
  faBell as farBell,
  faUser as farUser,
  faAngry as farAngry,
  faFrown as farFrown,
  faFrownOpen as farFrownOpen,
  faGrinAlt as farGrinAlt,
  faGrinBeamSweat as farGrinBeamSweat,
  faGrinHearts as farGrinHearts,
  faLaughBeam as farLaughBeam,
  faMeh as farMeh,
  faMehBlank as farMehBlank,
  faMehRollingEyes as farMehRollingEyes,
  faSmileBeam as farSmileBeam,
  faSurprise as farSurprise,
  faTired as farTired
} from "@fortawesome/free-regular-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

library.add(
  faAddressCard,
  faArrowLeft,
  faAssistiveListeningSystems,
  faBell,
  faBars,
  faCamera,
  faCaretDown,
  faChartBar,
  faChartLine,
  faChartPie,
  faChevronDown,
  faChevronRight,
  faCircle,
  faCog,
  faCommentAlt,
  faCommentDots,
  faDownload,
  faEdit,
  faEnvelope,
  faEraser,
  faExclamationCircle,
  faFileCode,
  faFileCsv,
  faFileExcel,
  faFilter,
  faKey,
  faLaptop,
  faLevelUpAlt,
  faListOl,
  faLock,
  faMinus,
  faPhone,
  faPlay,
  faPlus,
  faQuestion,
  faReceipt,
  faRedo,
  faSearch,
  faShoppingCart,
  faSignOutAlt,
  faSpinner,
  faSquare,
  faStop,
  faTable,
  faTimes,
  faTrash,
  faUndo,
  faUnlock,
  faUser,
  faUserCheck,
  faUserCog,
  faUsers,
  farBell,
  farUser,
  farAngry,
  farFrown,
  farFrownOpen,
  farGrinAlt,
  farGrinBeamSweat,
  farGrinHearts,
  farLaughBeam,
  farMeh,
  farMehBlank,
  farMehRollingEyes,
  farSmileBeam,
  farSurprise,
  farTired
);

Vue.component("font-awesome-icon", FontAwesomeIcon);

dom.watch(); // This will kick of the initial replacement of i to svg tags and configure a MutationObserver

export { FontAwesomeIcon };
